#3306 is default port for mysql 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cacheoperations?useSSL=false
    username: root
    password: Superkool@2025


#JPA Settings create/update
  jpa.hibernate.ddl_auto: update

#cache:
#   maxCacheSize:10